config/routes.rb
Treehouse::Application.routes.draw do
  get "profiles/show"

  devise_for :users
  
  devise_scope :user do
     get 'register', to: 'devise/registrations#new', as: :register
     get 'login', to: 'devise/sessions#new', as: :login
     get 'logout', to: 'devise/sessions#destroy', as: :logout
  end
  
  resources :user_friendships

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 2}

  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :email, :password, :password_confirmation, :remember_me,
                   :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                           with: /^[a-zA-Z0-9_-]+$/,
                           message: 'Must be formatted correctly'
                           }


  has_many :statuses 
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  def full_name
  	first_name + " " + last_name

  end

  def to_param
    profile_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end


end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user 
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  attr_accessible :user, :friend, :user_id, :friend_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  	    @statuses = @user.statuses.all 
  		render actions: :show
  	else
  	    render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])   
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end
    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!, only:[:new]
	
	def new
		if params[:friend_id]
			@friend = User.where(profile_name: params[:friend_id]).first
			raise ActiveRecord::RecordNotFound if @friend.nil?
			@user_friendship = current_user.user_friendships.new(friend: @friend)

		else
			flash[:error] = "Friend required"
		end

	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-mess"
		when :notice
			"notice-mess"
		else
			""
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="HandheldFriendly" content="true">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">

  <title>Statustree</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
  
</head>
<body>
  <header class="header-wrapper">
    <section class="nav-wrap"> 
      <h1 class="identity"><%= link_to "Statustree", statuses_path %></h1>
  
      <ul class="nav-list">
         <li><%= link_to "All Statuses", feed_path %></li>
      </ul>

      <ul class="nav-login">
        <% if user_signed_in? %>
         <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
         <li><%= link_to "Log Out", logout_path %></li>
           
           <% else %>
           <li><%= link_to "Register", register_path %></li>
           <li><%= link_to "Log in", login_path %></li>

         <% end %>
      </ul>

    </section>
  </header>
  <div class="page-wrap"> 
    
    <% flash.each do |type, message| %>
        <div class="alert <%= flash_class type %>">
             <%= message %>    
        </div>
    <% end %>

     <%= yield %>

  <footer>@2013 - Statustree</footer>
  </div>

</body>
</html>

app/views/profiles/show.html.erb
<section class="profile-header">
  <h2><%= @user.full_name %></h2>
   <%= link_to "Add A Friend", new_user_friendship_path(friend_id: @user),class: 'submit-btn' %>

</section>
  <% if @statuses %>
   <% @statuses.each do|status| %>
   
   <section class="status clearfix">
      <p><%= status.content %></p>
        <div class="meta">
          <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        </div>
    </section>
   <% end %>
  <% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 
    <%= f.label :content, class: "form-label", name: "Update your status" %>
    <%= f.text_area :content, class: "form-text" %>
 
  <div class="actions">
    <%= f.submit class:"submit-btn" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h2>Editing status</h2>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<!-- <h1 class="masthead">What to share your thought and meet new friends?<br/> share your status now on statustree !  <p class="new-register"><%= link_to "Register now!", register_path %></p></h1> -->

<h2></h2>
<%= link_to "Post A New Status", new_status_path, class: "btn-status" %>
<section class="new-post-wrapper clearfix">
<% @statuses.each do |status| %>
 </section>
 <section class="status clearfix">
  <span class="avatar">

   <%= link_to image_tag(status.user.gravatar_url),profile_path(status.user) %>
   
   </span> 

  <h4>
    <%= link_to status.user.full_name, status %>

  </h4>
    <p> <%= truncate status.content, length:180 %> </p>

   <div class="meta">
     <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
     <span class="admin">
       <span class="edit-admin"><%= link_to "Edit", edit_status_path(status)  %></span>
        <span class="delete-admin"><%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %></span>
     </span>
   </div>
 
<% end %>
</section>

app/views/statuses/new.html.erb
<h2>Post a new status update</h2>
<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @status.user.full_name %>
</h2>

<p>
  <%= @status.content %>
</p>

<div class="content-edit">
<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %></div>

app/views/user_friendships/new.html.erb
<% if @friend %>

<h2><%= @friend.full_name %></h2>

<p>Do you really want to friend <%= @friend.full_name %>? </p>

   <%= form_for @user_friendship, method: :post do |form| %>
      <div class="friendship form-actions">
      	<%= form.hidden_field :friend_id, value: @friend %>
          <%= submit_tag "Yes, Add this friend", class: 'submit-btn' %>
          <%= link_to "No, don't Add",profile_path(@friend), class: 'submit-btn' %>
   <% end %>
<% end %>